package ru.betel.domain.model.ui

enum class ActionBarState(val rout :String) {
    HOME_SCREEN("HOME_SCREEN"),
    TEMPLATE_SCREEN("TEMPLATE_SCREEN"),
    CATEGORY_SCREEN("CATEGORY_SCREEN"),
    SINGLE_SONG_SCREEN("SINGLE_SONG_SCREEN"),
    SINGLE_TEMPLATE_SCREEN("SINGLE_TEMPLATE_SCREEN"),
    NEW_SONG_SCREEN("NEW_SONG_SCREEN"),
    NEW_TEMPLATE_SCREEN("NEW_TEMPLATE_SCREEN"),
    FAVORITE_SCREEN("FAVORITE_SCREEN"),
}