package ru.betel.domain.model.ui

enum class Screens(val actionBarState: ActionBarState, val route: String) {
    HOME_SCREEN(ActionBarState.HOME_SCREEN, "HOME_SCREEN"),
    TEMPLATE_SCREEN(ActionBarState.TEMPLATE_SCREEN, "TEMPLATE_SCREEN"),
    CATEGORY_SCREEN(ActionBarState.CATEGORY_SCREEN, "CATEGORY_SCREEN"),
    FAVORITE_SCREEN(ActionBarState.FAVORITE_SCREEN, "FAVORITE_SCREEN"),
    NEW_SONG_SCREEN(ActionBarState.NEW_SONG_SCREEN, "NEW_SONG_SCREEN"),
    NEW_TEMPLATE_SCREEN(ActionBarState.NEW_TEMPLATE_SCREEN, "NEW_TEMPLATE_SCREEN"),
    TEMPLATES_SONGS_SCREEN(ActionBarState.CATEGORY_SCREEN, "TEMPLATES_SONGS_SCREEN"),
    SINGLE_SONG_SCREEN(ActionBarState.SINGLE_SONG_SCREEN, "SINGLE_SONG_SCREEN"),
    SINGLE_TEMPLATE_SCREEN(ActionBarState.SINGLE_TEMPLATE_SCREEN, "SINGLE_TEMPLATE_SCREEN"),
    EDIT_TEMPLATE_SCREEN(ActionBarState.SINGLE_TEMPLATE_SCREEN, "EDIT_TEMPLATE_SCREEN"),
    EDIT_SONG_SCREEN(ActionBarState.SINGLE_TEMPLATE_SCREEN, "EDIT_SONG_SCREEN"),

}