package ru.betel.app.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Color.Companion.Black


val actionBarColor = Color(0xFF002C85)
val topOfActionBarColor = Color(0xFF022976)
val actionBarTextColor = Color(0xFFFFFFFF)
val fieldBg = Color(0xFFF4F6FF)
val textFieldPlaceholder = Color(0xFF756F86)
val dividerColor = Color(0xFFC4C4C4)
val appTextColor = Color(0xFF111111)
val songDividerColor = Color(0xFFEDEDED)
val drawerLayoutSecondaryColor = Color(0xFFF4F6FF)
val menuTextSelectedColor = Color(0xFF756F86)
val menuTextUnselectedColor = Color(0xFF111111)

val primary_bgColor = Color(0xFFffffff)
val primary_actionbarIconColor = Color(0xFFFFFFFF)
val primary_actionBarColor = Color(0xFF002C85)
val primary_actionStatusBarColor = Color(0xFF002C85)
val primary_dividerColor = Color(0xFFEDEDED)
val primary_primaryTextColor = Color(0xFF111111)
val primary_secondaryTextColor = Color(0xFF756F86)
val primary_fieldTextColor = Color(0xFF756F86)
val primary_primaryIconColor = Color(0xFF000000)
val primary_primaryButtonColor = Color(0xFF002C85)
val primary_secondaryButtonColor = Color(0xFFF4F6FF)
val primary_selectedBoxColor = Color(0xFF002C85)
val primary_unselectedBoxColor = Color(0xFF756F86)
val primary_screenBackgroundColor = Color(0xFFffffff)
val primary_drawerIconColor = Color(0xFF002C85)
val primary_drawerIconBackgroundColor = Color(0xFFF4F6FF)

val gray_bgColor = Color(0xFF2B3131)
val gray_actionbarIconColor = Color(0xFFDDDFDE)
val gray_actionBarColor = Color(0xFF2B3131)
val gray_actionStatusBarColor = Color(0xFF2B3131)
val gray_dividerColor = Color(0xFF454B4B)
val gray_primaryTextColor = Color(0xFFFEFFFF)
val gray_secondaryTextColor = Color(0xFF9AA0A0)
val gray_fieldTextColor = Color(0xFF756F86)
val gray_primaryIconColor = Color(0xFFCDCED0)
val gray_primaryButtonColor = Color(0xFF383E3E)
val gray_secondaryButtonColor = Color(0xFF444A4A)
val gray_selectedBoxColor = Color(0xFFDDDFDE)
val gray_unselectedBoxColor = Color(0xFF756F86)
val gray_screenBackgroundColor = Color(0xFF2B3131)
val gray_drawerIconColor = Color(0xFFDDDFDE)
val gray_drawerIconBackgroundColor = Color(0xFF2B3131)